### ISSUE TITLE
Seperattion

### ISSUE THREAD

**Issue by B0yc3y** [B0yc3y/project3#4]
Hey, I just had a look and I think we have to split it up even moreso, so think of regression as the abstract class for any curve fitting, and poly, exp, linear and log are where the logic for each type of regression goes. they extend the regression class.

**Comment by alvinng92** [comment]
Yeah i saw the subclasses. I just wanted to get something functional first and also didn't know how to extend methods into other models without having something clunky like
Regression.new
Regression.create_linear(linearmethod)
Regression.create_poly(polymethod)
Regression.create_log (logmethod)
etc

**Comment by B0yc3y** [comment]
So thats why we have the curvefit model, the curvefit model will have a best_fit method which creates  the 4 regression objects and calculates which is the best. the poly/exp/log/linear are all children of the regression class, so pred = curvefit.new

and initialize in curvefit will create the 4, compare them and return the best.
